CREATE TABLE `visitor_feedback` (
	`id` int AUTO_INCREMENT NOT NULL,
	`visitorId` varchar(100) NOT NULL,
	`sessionId` varchar(100),
	`userId` int,
	`feedbackType` enum('missing_feature','improvement','high_value','joy_factor','general') NOT NULL,
	`content` text NOT NULL,
	`currentPage` varchar(255),
	`conversationHistory` text,
	`timeOnSite` int,
	`sentiment` enum('positive','neutral','negative'),
	`priority` enum('low','medium','high','critical') DEFAULT 'medium',
	`status` enum('new','reviewed','planned','implemented','rejected') NOT NULL DEFAULT 'new',
	`ownerNotes` text,
	`userAgent` text,
	`device` varchar(50),
	`browser` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`reviewedAt` timestamp,
	`implementedAt` timestamp,
	CONSTRAINT `visitor_feedback_id` PRIMARY KEY(`id`)
);
